version: '3'

services:
  postgres:
    container_name: e-voting-master-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: e_voting_master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15434:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    networks:
      - app-tier
  redis:
    container_name: e-voting-master-postgres-redis
    image: redis:7.2
    volumes:
      - ./volumes/redis:/data
    ports:
      - "16380:6379"
    networks:
      - app-tier

volumes:
  postgres:
